CREATE TABLE roles(
	id INT AUTO_INCREMENT,
	role ENUM("USER_COMUM", "USER_SUBADMIN", "USER_ADMIN") NOT NULL UNIQUE,
	
	PRIMARY KEY(id)
);

ALTER TABLE users
ADD COLUMN role INT,
ADD FOREIGN KEY(role) REFERENCES roles(id);