INSERT IGNORE INTO roles (role) VALUES ('USER_COMUM');

UPDATE users SET role = (SELECT id FROM roles WHERE role = "USER_COMUM" LIMIT 1)
WHERE role IS NULL;

ALTER TABLE users MODIFY COLUMN role INT NOT NULL;